Month7/step2
0xFED1A/react-burger pull request #1
Opened 2022-12-10 03:31 UTC by 0xFED1A

Pull request to merge branch moth7/step2 into main

2022-12-10 05:06 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализованы модальные окна;
- Реализовано получение данных с сервера.

### **Но есть несколько замечаний, которые нужно исправить (в основном замечания отмечены в коде):**

- Оберните иконку в шапке в ссылку `<a href="/#">`

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили. Проверьте во всём проекте.

- Поправьте работу с сервером.

- Не используйте ref, только для того чтобы повесить на элемент `mouseDown` и т.п. события, которые можно установить инлайново.

- По макету, у булок в `burger-constructor` должна быть приписка - `(верх) (низ)`

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-10 17:24 UTC, 0xFED1A commented on src/index.tsx
> +  )
Исправлено, теги <React.StrictMode></React.StrictMode> возвращены на место.

2022-12-10 17:35 UTC, 0xFED1A commented on src/components/App/app.jsx
> +  const URL = "https://norma.nomoreparties.space/api/ingredients";
Сделано. BURGER_API_URL в  /utils/constants.js

2022-12-10 20:38 UTC, 0xFED1A commented on src/components/App/app.jsx
> +    };
исправлено

2022-12-10 21:34 UTC, 0xFED1A commented on src/components/App/app.jsx
> +        }
Теперь компонент <Modal> больше не монтируется в <App>. Это происходит в <BurgerIngredients> и <BurgerConstructor>

2022-12-10 21:38 UTC, 0xFED1A commented on src/components/App/app.jsx
> +    return (
упрощено

2022-12-10 22:02 UTC, 0xFED1A commented on src/components/AppHeader/app-header.jsx
> +          </a>
починено

2022-12-10 22:08 UTC, 0xFED1A commented on src/components/BurgerConstructor/burger-constructor.jsx
> +  }
Функция рассчёта высоты удалена.

2022-12-10 23:17 UTC, 0xFED1A commented on src/components/BurgerConstructor/burger-constructor.jsx
> +  }
сделано

2022-12-10 23:17 UTC, 0xFED1A commented on src/components/BurgerConstructor/burger-constructor.jsx
> +    const bottomIngredient = allIngredients[allIngredients.length - 1];
сделано

2022-12-10 23:17 UTC, 0xFED1A commented on src/components/BurgerConstructor/burger-constructor.jsx
> +            text={topIngredient.name}
сделано

2022-12-10 23:18 UTC, 0xFED1A commented on src/components/BurgerConstructor/burger-constructor.jsx
> +            extraClass=""
сделано

2022-12-10 23:18 UTC, 0xFED1A commented on src/components/BurgerConstructor/burger-constructor.jsx
> +          style={{maxHeight: calcSaneHeight(80, 16)}}
сделано

2022-12-10 23:19 UTC, 0xFED1A commented on src/components/BurgerConstructor/burger-constructor.jsx
> +  function populateUsedIngredients() {
сделано

2022-12-10 23:28 UTC, 0xFED1A commented on src/components/BurgerConstructor/burger-constructor.jsx
> +              key={item["_id"]}
сделано

2022-12-10 23:50 UTC, 0xFED1A commented on src/components/BurgerConstructor/burger-constructor.jsx
> +export default function BurgerConstructor(props) {
сделано

2022-12-11 00:01 UTC, 0xFED1A commented on src/components/BurgerIngredients/burger-ingredients.jsx
> +      props.ingredientsList.filter(item => item.type === ingredientType);
сделано

2022-12-11 00:01 UTC, 0xFED1A commented on src/components/BurgerIngredients/burger-ingredients.jsx
> +  function populateAvailableIngredients(ingredientType) {
сделано

2022-12-11 00:05 UTC, 0xFED1A commented on src/components/BurgerIngredients/burger-ingredients.jsx
> +  ingredientsList: PropTypes.arrayOf(ingredientObjectProp).isRequired,
сделано

2022-12-11 01:16 UTC, 0xFED1A commented on src/components/Modal/modal.jsx
> +  const closeButtonRef = useRef(null);
сделано

2022-12-11 01:26 UTC, 0xFED1A commented on src/components/Modal/modal.jsx
> +  children: PropTypes.element,
сделано

2022-12-11 01:29 UTC, 0xFED1A commented on src/components/ModalOverlay/modal-overlay.jsx
> +  const overlayDivRef = useRef(null);
исправлено

2022-12-11 01:30 UTC, 0xFED1A commented on src/components/ModalOverlay/modal-overlay.jsx
> +  children: PropTypes.element,
есть

2022-12-11 08:26 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Все замечания с прошлого ревью были исправлены.

### **Но ещё есть несколько замечаний, которые нужно исправить:**

- Отметил пару небольших замечаний в коде.

### **Сделает код лучше:**

- при клике на таб скролить список ингредиентов к нужному разделу.

2022-12-11 08:26 UTC, ArslanDev666 commented on src/components/App/app.jsx
> +  useEffect(() => {getIngredientsList(setIngredeintsList)}, []);
**Надо исправить:**

Не нужно передавать callback, это сильно ограничит функциональность. 
Лучше всего, просто возвращать ответ, и уже в `.then` добавлять данные в нужный стейт.

```js
getIngredientsList()
  .then(res => setIngredientsList(res.data))
  .catch(() => /** что-то делать с ошибкой */)
  .finally(() => /** что-то делать с лоадером */)
```

Вообщеи, фукнция запроса должна возвращать только ответ от сервера.

2022-12-11 08:26 UTC, ArslanDev666 commented on src/components/BurgerIngredients/burger-ingredients.jsx
> +                    onClick={handleOpenModal}
**Можно лучше:**

Тут можно через анонимную функцию передавать `_id` ингредиента.

```js
onClick={() => handleOpenModal(item._id)}
```

Тут использование анонимной функции не критично, ибо контент у нас не будет меняться, и рендериться множество раз.

2022-12-11 08:26 UTC, ArslanDev666 commented on src/components/BurgerIngredients/burger-ingredients.jsx
> +            </ul>
**Можно лучше**

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его

2022-12-11 08:26 UTC, ArslanDev666 commented on src/components/Modal/modal.jsx
> +      closeButton.removeEventListener("click", handleCloseOnButtonClick);
**Надо исправить:**

Тут не нужно это делать, т.к. при размонтировании обработчик сам снимется с элемента.
Когда компонент размонтируется, `<div>` элемент удаляется из DOM. Если элемент удаляется из DOM, все его прослушиватели событий также удаляются.

2022-12-11 15:39 UTC, 0xFED1A commented on src/components/BurgerIngredients/burger-ingredients.jsx
> +                    onClick={handleOpenModal}
Сделано. Теперь handleOpenModa() принимает не event а id ингредиента. Атрибут id удалён.

2022-12-11 15:39 UTC, 0xFED1A commented on src/components/BurgerIngredients/burger-ingredients.jsx
> +            </ul>
Сделано. Свёрстан отдельный компонент IngredientsCategory.

2022-12-11 17:17 UTC, 0xFED1A commented on src/components/Modal/modal.jsx
> +      closeButton.removeEventListener("click", handleCloseOnButtonClick);
Сделано

2022-12-11 18:18 UTC, 0xFED1A commented on src/components/App/app.jsx
> +  useEffect(() => {getIngredientsList(setIngredeintsList)}, []);
Сделано

2022-12-12 01:02 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены.

2022-12-12 10:57 UTC, merged